trigger: none

pool:
  vmImage: 'macOS-10.14'

steps:

- task: UseNode@1
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.x'
    addToPath: true
    architecture: 'x64'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'GlobFinder cert.p12'
    certPwd: $(p12Password)
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Glob_Finder_Distribution.mobileprovision'

- script: yarn
  workingDirectory: cordova
  displayName: 'Get dependencies'

- script: yarn cordova prepare
  workingDirectory: cordova
  displayName: 'Fetch platforms and plugins'

- script: yarn cordova build ios --release --codeSignIdentity="iPhone Developer" --developmentTeam=YWCQ65XXP9 --packageType=app-store --provisioningProfile=$(APPLE_PROV_PROFILE_UUID) --automaticProvisioning=false
  workingDirectory: cordova
  displayName: 'Build app'
