# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: ProvideNPMToken@0
  inputs:
    npmTokenSecureFile: 'npmToken'
- script: |
    echo $(npm_config_registry)
    env
  displayName: 'Run a one-line script'


