trigger: none

pool:
  vmImage: 'macOS-10.14'

steps:
- task: UseNode@1

- script: yarn
  workingDirectory: electron
  displayName: 'Get deps'

- script: yarn build:native
  workingDirectory: electron

- script: yarn dist
  workingDirectory: electron

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/dist'
    artifact: 'app'
    publishLocation: 'pipeline'