trigger: none

pool:
  vmImage: 'macOS-10.14'

steps:

- task: UseNode@1
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.x'
    addToPath: true
    architecture: 'x64'

- script: yarn
  workingDirectory: electron
  displayName: 'Get dependencies'

- script: yarn build:native
  workingDirectory: electron
  displayName: 'Build native module'

- script: yarn dist
  workingDirectory: electron
  displayName: 'Build app'
